#!/usr/bin/env python
import sys
import os
import shutil
from StringIO import StringIO
from hashlib import md5
import filecmp
import logging
import numpy
import time
# This avoids installing nprlib module. npr script will find it in the
# same directory in which it is
NPRPATH = os.path.split(os.path.realpath(__file__))[0]

sys.path.insert(0, NPRPATH)
from nprlib import argparse 
from nprlib.configobj import ConfigObj, flatten_errors
from nprlib import validate
from nprlib.utils import SeqGroup, generate_runid,  AA, NT, GLOBALS
from nprlib.errors import ConfigError, DataError
from nprlib.master_task import Task
from nprlib.interface import app_wrapper
from nprlib.scheduler import schedule
from nprlib import db
from nprlib import apps
    
try:
    module_path = os.path.split(__file__)[0]
    __VERSION__ = open(os.path.join(module_path, "VERSION")).read().strip()
except: 
    __VERSION__ = "unknown"

try:
    module_path = os.path.split(__file__)[0]
    __DATE__ = open(os.path.join(module_path, "DATE")).read().strip()
except: 
    __DATE__ = "unknown"

__DESCRIPTION__ = (
"""--------------------------------------------------------------------------------
                 Nested Phylogenetic Reconstruction program.  
                          NPR-0.1%s(beta), %s.

      NPR allows to reconstruct large phylogenies by means of an
      iterative strategy that provides scalable resolution along the
      different tree levels. Using NPR, internal nodes are
      re-evaluated to optimize and fine tune the parameters of the
      phylogenetic inference.

      If you use this program in a published work, please cite:

        Jaime Huerta-Cepas and Toni Gabaldon. Nested Phylogenetic
        Reconstruction. XXX-XX. 2012.

      (Note that a list of external programs used to complete the
      necessary computations will be shown shown together with your
      results.)

      Contact: jhuerta [at] crg.es, tgabaldon [at] crg.es
--------------------------------------------------------------------------------

    """ %(__VERSION__, __DATE__))

def existing_file(value):
    if os.path.isfile(value):
        return value
    else:
        raise ConfigError("Not valid file")

def check_number(value, cast, minv=0, maxv=None):
    try:
        typed_value = cast(value)
    except ValueError:
        raise ConfigError("Expected [%s] number. Found [%s]" %(cast, value))
    else:
        if (minv is not None and typed_value < cast(minv)) or \
           (maxv is not None and typed_value > cast(maxv)):
            _minv = minv if minv is not None else "any"
            _maxv = maxv if maxv is not None else "any"
            raise ConfigError("[%s] not in the range (%s,%s)" %
                              (value, _minv, _maxv))
    return typed_value

def is_float(value, minv=None, maxv=None):
    return check_number(value, float, minv, maxv)

def is_integer(value, minv=None, maxv=None):
    return check_number(value, int, minv, maxv)

def is_list(value):
    if not isinstance(value, list):
        raise ConfigError("Expected a list of values. Found [%s]" %value)
    return value
    
def is_boolean_list(value):
    is_list(value)
    typed_value = []
    for v in value:
        typed_value.append(check_number(v, bool, 0, 1))
    return typed_value
    
def is_float_list(value, minv=0, maxv=None):
    is_list(value)
    typed_value = []
    for v in value:
        typed_value.append(check_number(v, float, minv, maxv))
    return typed_value

def is_integer_list(value, minv=0, maxv=None):
    is_list(value)
    typed_value = []
    for v in value:
        typed_value.append(check_number(v, int, minv, maxv))
    return typed_value
    
def main(args):
    base_dir = GLOBALS["basedir"]
    log = logging.getLogger("main")
    print __DESCRIPTION__
 
    local_conf_file = os.path.join(base_dir, "pipeline.cfg")
    if os.path.exists(base_dir):
        if os.path.exists(local_conf_file):
            if not args.override and \
               not filecmp.cmp(args.configfile, local_conf_file):
                raise ConfigError("Output directory seem to contain"
                                  " a NPR execution using a different"
                                  " config file [pipeline.cfg]. Use"
                                  " --override option or change the "
                                  " output path.")
 
    config = ConfigObj(args.configfile, list_values=True)
 
    try:
        npr_template = config["main"]["template"]
    except KeyError:
        raise ConfigError("Bad config file. A template name or file should be specified.")
   
    if npr_template == "genetree":
        from nprlib.template.genetree import pipeline, config_specs
        config = ConfigObj(args.configfile, list_values=True,
                           configspec=StringIO(config_specs))
    else:
        raise ConfigError("Bad template [%s]" %npr_template)
       
    custom_types = {"boolean_list": is_boolean_list, 
                    "integer_list": is_integer_list,
                    "float_list": is_float_list,
                    "float": is_float,
                    "integer": is_integer,
                    "list": is_list,
                    }
    val = validate.Validator(custom_types)
    check = config.validate(val)
    if not check:
        print flatten_errors(config, check)
        raise ConfigError("Bad config file")
       
    # Check for unique max_seq config values
    if len(config["main"]["npr_max_seqs"]) != \
            len(set(config["main"]["npr_max_seqs"])):
        raise ConfigError("Duplicated entries in 'npr_max_seqs'.")

    # Check for unique max_seq config values
    if config["main"]["npr_max_seqs"] != \
            sorted(config["main"]["npr_max_seqs"]):
        print sorted(config["main"]["npr_max_seqs"])
        raise ConfigError("'npr_max_seqs' values must be in ascending order.")

    # Check that fields are filled for all max_seq values
    conf_keys = [v for v in config["main"] if v.startswith("npr_")]
    if len(set([len(config["main"][v]) for v in conf_keys])) != 1:
        raise ConfigError("Unequal length of main NPR config table.")

    if args.arch == "auto":
        if sys.maxsize > 2**32:
            arch = "64"
        else:
            arch = "32"
    else:
        arch = args.arch
    
    APPSPATH = os.path.join(NPRPATH, "apps/x86-%s" %arch)
    # setup portable apps
    for k,v in config["app"].iteritems():
        if v == "built-in":
            if args.sge_execute:
                _apps_path = os.path.realpath(config["sge"]["remote_npr_path"])
                cmd = apps.get_call(k, _apps_path, base_dir) 
                config["app"][k] = cmd
            else:
                cmd = apps.get_call(k, APPSPATH, base_dir) 
                config["app"][k] = cmd
    #log.debug('\n'.join(["%s\t%s" %(i,j) for i,j in config["app"].items()]))
    if not args.nochecks:
        print "Testing x86-%s portable applications..." % arch
        apps.test_apps(config["app"])
    
    # Set number of CPUs available
    config["main"]["_max_cores"] = args.maxcores
    log.debug("Enabling %d CPU cores" %args.maxcores)

    # Create dir structure
    gallery_dir = os.path.join(base_dir, "gallery")
    sge_dir = os.path.join(base_dir, "sge_jobs")
    tmp_dir = os.path.join(base_dir, "tmp")
    tasks_dir = os.path.join(base_dir, "tasks")
    GLOBALS["sge_dir"] = sge_dir
    GLOBALS["tmp"] = tmp_dir
    GLOBALS["gallery_dir"] = gallery_dir
    GLOBALS["tasks_dir"] = tasks_dir
    for dirname in [gallery_dir, sge_dir, tmp_dir, tasks_dir]:
        try:
            os.makedirs(dirname)
        except OSError:
            log.warning("Using existing dir: %s", dirname)
    # Initialize db
    db.init_db(os.path.join(base_dir, "db.sqlite3"))

    # Copy config file
    shutil.copy(args.configfile, os.path.join(base_dir, "pipeline.cfg"))

    # check nt_seed and aa_seed. Do they contain the same seqs?
    # format? names?
    visited_seqs = set()
    seed_files = {}
    seq2aalength = {}
    seq2ntlength = {}
    for label, seq_file, seq2length in [["aa_seed", args.aa_seed_file, seq2aalength],
                                        ["nt_seed", args.nt_seed_file, seq2ntlength]]:
        if seq_file: 
            SEQS = SeqGroup(seq_file, fix_duplicates=False)
            # Loads seq lengths
            for seqid, seq in SEQS.id2seq.iteritems():
                seqname = SEQS.id2name[seqid]
                if args.unalign:
                    seq = seq.replace("-", "").replace(".", "")
                    SEQS.id2seq[seqid] = seq
                    
                seq2length[seqname] = len(seq)
                if label == "nt_seed" and set(seq)-NT:
                    error = "Unknown symbols [%s] in sequence [%s] of file [%s]" %\
                        (''.join(set(seq)-NT), seqname, seq_file)
                    raise DataError(error)
                elif label == "aa_seed" and set(seq)-AA:
                    error = "Unknown symbols [%s] in sequence[%s] of file [%s]" %\
                        (''.join(set(seq)-AA), seqname, seq_file)
                    raise DataError(error)

            id2name = {}
            for i,n in SEQS.id2name.iteritems():
                if args.seq_rename:
                    # This is a bit tricky. I want to generate 10 char
                    # unique names that are the always the same for
                    # identical original names. Hash functions cannot
                    # generate less than 16 bits strings, so I will
                    # trust in the first 10 chars. It is very unlikely
                    # to get a collision even in large sets (million
                    # of names.), but in such a case, I will raise an
                    # error.
                    name = md5(n).hexdigest()[:10]
                    id2name[name] = SEQS.id2name[i]
                    SEQS.id2name[i] = name

                elif len(n)>10: 
                    SEQS.id2name[i] = n[:10]
                    log.warning("sequence name %s was truncated to 10"
                                " chars: %s " %(n, n[:10]))

            values = set(SEQS.id2name.values())
            if len(values) != len(set(values)):
                if args.seq_rename:
                    raise DataError("Although collisions in the hash function"
                                    " used to generate unique sequence names"
                                    " are very unlikely, you have found an "
                                    " exception!. Please, change seq names "
                                    " manually.")
                else:
                    raise DataError("Duplicated sequence names, execution"
                                    " aborted. Correct manually or set"
                                    " automatic sequence renaming with"
                                    " --seq_rename flag.")
                    
            if visited_seqs and visited_seqs - values:
                print visited_seqs - values
                raise DataError("Sequence names do not match between aa and"
                                " nt files.")
            elif visited_seqs and values - visited_seqs:
                log.warning("%d nucleotide sequences will not be used" % 
                            len(values - visited_seqs))
            visited_seqs.update(values)
            fullpath = os.path.join(base_dir, label+".fasta")
            seed_files[label] = fullpath
            SEQS.write(outfile=fullpath)

    if id2name: 
        id_conversion_file = os.path.join(base_dir, "id_conversion.txt")
        CONV = open(id_conversion_file, "w")
        for i,v in id2name.iteritems():
            CONV.write("%s\t%s\n" %(i,v))
            try:
                db.add_seq_name(i, v)
            except db.sqlite3.IntegrityError:
                pass
                
        CONV.close()
        db.commit()
        
    config["main"]["aa_seed"] =  seed_files.get("aa_seed", None)
    config["main"]["nt_seed"] =  seed_files.get("nt_seed", None)

    if seq2ntlength and seq2aalength:
        for seqname, length in seq2aalength.iteritems():
            try:
                if length != seq2ntlength[seqname]/3.0:
                    raise DataError("The length of [%s] CDS does not match"
                                     " protein sequence." %seqname)
            except KeyError:
                raise DataError("aa and nt files do not contain the same"
                               "sequence identifiers.")
                
    # Sequence lengths analysis
    if seq2aalength:
        all_len = seq2aalength.values()
    else:
        all_len = seq2ntlength.values()
   
    max_len = numpy.max(all_len)
    min_len = numpy.min(all_len)
    mean_len = numpy.mean(all_len)
    std_len = numpy.std(all_len)
    outliers = []
    for v in all_len:
        if abs(mean_len - v) >  (2 * std_len):
            outliers.append(v)
    log.log(28, "Max sequence length:  %d" %max_len)
    log.log(28, "Min sequence length:  %d" %min_len)
    log.log(28, "Mean sequence length: %d +- %0.1f " %(mean_len, std_len))
    if outliers:
        log.warning("%d sequence lengths look like outliers" %len(outliers))

    # how task will be executed
    if args.execute:
        if args.nodetach:
            execution = ("insitu", False)
        else:
            execution =("insitu", True)
    elif args.sge_execute:
        execution = ("sge", False)
    else:
        execution = (None, False)
        
    # Scheduling starts here
    schedule(config, pipeline, args.schedule_time, 
             execution, args.retry, args.debug)

    if args.compress:
        log.log(20, "Compressing files from intermediate steps...")
        cmd = "cd %s && find -t d -maxdepth 1 -exec tar -jcf {}.tar.bz2 {} \;" %GLOBALS["basedir"]
        print cmd
                

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__DESCRIPTION__, 
                            formatter_class=argparse.RawDescriptionHelpFormatter)
    # name or flags - Either a name or a list of option strings, e.g. foo or -f, --foo.
    # action - The basic type of action to be taken when this argument is encountered at the command line. (store, store_const, store_true, store_false, append, append_const, version)
    # nargs - The number of command-line arguments that should be consumed. (N, ? (one or default), * (all 1 or more), + (more than 1) )
    # const - A constant value required by some action and nargs selections. 
    # default - The value produced if the argument is absent from the command line.
    # type - The type to which the command-line argument should be converted.
    # choices - A container of the allowable values for the argument.
    # required - Whether or not the command-line option may be omitted (optionals only).
    # help - A brief description of what the argument does.
    # metavar - A name for the argument in usage messages.
    # dest - The name of the attribute to be added to the object returned by parse_args().

  
    # Input data related flags
    input_group = parser.add_argument_group('INPUT OPTIONS:')
    input_group.add_argument("-a", dest="aa_seed_file", 
                        type=existing_file, 
                        help="Initial multi sequence file with"
                        " protein sequences")

    input_group.add_argument("-n", dest="nt_seed_file", 
                        type=existing_file, 
                        help="Initial multi sequence file with"
                        " nucleotide sequences")

    input_group.add_argument("--seq_rename", dest="seq_rename", 
                        action="store_true",
                        help="If used, seq names are internally converted"
                        " to get safe and unique 10 char identifiers.")

    input_group.add_argument("--dealign", dest="unalign", 
                        action="store_true",
                        help="If used, gaps in the orginal fasta file are"
                        " removed.")

    # Output data related flags
    output_group = parser.add_argument_group('OUTPUT OPTIONS:')
    output_group.add_argument("-o", "--outdir", dest="outdir", 
                        type=str, required=True, 
                        help="""Output directory for results.""")

    output_group.add_argument("--compress", action="store_true",
                        help="Compress intermediate files when"
                              " task is finished.")
    
    # Task execution related flags
    exec_group = parser.add_argument_group('EXECUTION OPTIONS:')

    exec_group.add_argument("-c", "--config", dest="configfile", 
                        type=existing_file, required=True, 
                        help="NPR configuration file")
       
    exec_group.add_argument("-r", "--retry_error_jobs", dest="retry", 
                        action="store_true",
                        help="Try to relaunch, once more, jobs marked"
                        " as error.")
    
    exec_group.add_argument("-m", "--maxcores", dest="maxcores", type=int,
                        default=1, help="Maximum number of CPU cores"
                        " available in the execution hosts. If higher"
                        " than 1, tasks with multi-threading"
                        " capabilities will be set appropriately.")

    exec_group.add_argument("-t", "--schedule_time", dest="schedule_time", 
                        type=float, default=30.0,
                        help="""Schedule time in seconds. """)
    
    exec_type_group = exec_group.add_mutually_exclusive_group()
    exec_type_group.add_argument("-x", "--execute_insitu", dest="execute", 
                        action="store_true",
                        help="Jobs are launched in the same machine"
                        " as in the program is called.")

    exec_type_group.add_argument("--sge", dest="sge_execute",
                        action="store_true", help="Jobs will be"
                        " launched using the Sun Grid Engine"
                        " queue system.")

    exec_group.add_argument("--nodetach", dest="nodetach",
                        action="store_true", help="Jobs will not be"
                        " detached from the main NPR process. This means that"
                        " when npr execution is interrupted, all currently"
                        " running jobs will die with it. Use this option if you"
                        " want to execute the npr program as single shot job"
                        " (i.e. send npr jobs to a cluster). Note that"
                        " by default, npr is executed in monitor mode, so"
                        " launched jobs keeps running even when npr"
                        " process is killed." )
    
    exec_group.add_argument("--override", dest="override",
                            action="store_true",
                            help="Overrides previous configuration files" )
    
    exec_group.add_argument("--arch", dest="arch",
                            choices=["auto", "32", "64"],
                            default="auto", help="Set the architecture of"
                            " executuion hosts (needed only when using"
                            " built-in applications.)")
   
    # Interface related flags
    ui_group = parser.add_argument_group("INTERFACE OPTIONS")
    ui_group.add_argument("-u", dest="enable_ui",
                        action="store_true", help="When used, a color"
                        " based interface is launched to monitor NPR"
                        " processes. This feature is EXPERIMENTAL and"
                        " requires NCURSES libraries installed in your"
                        " system.")

    ui_group.add_argument("-v", dest="verbosity",
                        default = 0, type=int, choices=[0,1,2,3,4],
                        help="Verbosity level: 0=very quiet, 4=very "
                          " verbose.")
    
    ui_group.add_argument("--nochecks", dest="nochecks",
                          action="store_true", 
                          help="Skip application checks during the start-up")
   
    ui_group.add_argument("--debug", nargs="?",
                          const="all",
                          help="Starts a debugging"
                          " session. A taskid can be provided, so"
                          " debugging will start from such task on." 
                          )

    ui_group.add_argument("--logfile", action="store_true",
                          help="Log messages are also written into a file"
                      )
    
    args = parser.parse_args()

    if not args.aa_seed_file and not args.nt_seed_file:
        parser.error('At least one input file argument (-a, -n) is required')
    

    GLOBALS["basedir"] = os.path.abspath(args.outdir)
    GLOBALS["runid"] = generate_runid()
    if not os.path.exists(GLOBALS["basedir"]):
        os.makedirs(GLOBALS["basedir"])
  
    # Start the application
    app_wrapper(main, args)


