PRGS =  baseml codeml basemlg mcmctree pamp evolver yn00 chi2 
CC = cl # cc, gcc, cl
CFLAGS =  -O2 -Ot 

DEFINE = #
LIBS = #-lm -lM

all : $(PRGS)
 
baseml : baseml.c tools.c
  $(CC) $(CFLAGS) baseml.c tools.c $(LIBS)
basemlg : basemlg.c tools.c
  $(CC) $(CFLAGS) basemlg.c tools.c $(LIBS)
codeml : codeml.c tools.c
  $(CC) $(CFLAGS) codeml.c tools.c $(LIBS)
evolver : evolver.c tools.c
  $(CC) $(CFLAGS) evolver.c tools.c $(LIBS)
mcmctree : mcmctree.c tools.c
  $(CC) $(CFLAGS) mcmctree.c tools.c $(LIBS)
  $(CC) $(CFLAGS) -FemcmctreeHH.exe -DHardHard mcmctree.c tools.c $(LIBS)
  $(CC) $(CFLAGS) -FemcmctreeHS.exe -DHardSoft mcmctree.c tools.c $(LIBS)
pamp : pamp.c tools.c 
  $(CC) $(CFLAGS) pamp.c tools.c $(LIBS)
yn00 : yn00.c tools.c
  $(CC) $(CFLAGS) yn00.c tools.c $(LIBS)
chi2 : chi2.c
  $(CC) $(CFLAGS) chi2.c $(LIBS)
