#! /bin/sh
SCRIPT_DIR="$(dirname "$(readlink -f "${0}")")"
if [ $1 ] && [ -e $SCRIPT_DIR/ete_$1 ] 
then
    $SCRIPT_DIR/ete_$@
else
    echo
    echo "Usage:"
    echo "  ete TOOL_NAME [tool_arguments]"
fi 