#!/usr/bin/env python
import sys
import ete_tools

try:
    modname = "ete_%s"%sys.argv[1]
    main = getattr(getattr(__import__("ete_tools.%s" %modname), modname), "main")
except (AttributeError, IndexError, ImportError):
    print 'Tool not found!\n'
else:
    main(sys.argv[2:])




